### ISSUE TITLE
The issue of GTDB reference database

### ISSUE THREAD

**Issue by zh8008** [BigDataBiology/SemiBin#100]
Hello, how can I change the GTDB reference database? I want to upgrade to version 207 of gtdb database.

**Comment by psj1997** [comment]
Hi,

Thanks for your attention to the SemiBin.

You can use mmseqs databases to download version 207 of GTDB and put the downloaded file to the -r reference path (for example:$HOME/.cache/SemiBin/mmseqs2-GTDB).

Sincerely
Shaojun

**Comment by luispedro** [comment]
@zh8008 does this answer your question? Please let us know if you need more info

**Comment by zh8008** [comment]
I keep trying, but mmseqdatabase always keeps failing to download. Now I'm going to download the gtdb database and build the index with mmseq2. Is that ok?



发自我的iPhone


------------------ Original ------------------
From: Luis Pedro Coelho ***@***.***&gt;
Date: Sun,Jul 10,2022 6:23 AM
To: BigDataBiology/SemiBin ***@***.***&gt;
Cc: He Zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [BigDataBiology/SemiBin] The issue of GTDB reference database (Issue #100)





 
@zh8008 does this answer your question? Please let us know if you need more info

**Comment by zh8008** [comment]
Thanks for your explain！



发自我的iPhone


------------------ Original ------------------
From: Luis Pedro Coelho ***@***.***&gt;
Date: Sun,Jul 10,2022 6:23 AM
To: BigDataBiology/SemiBin ***@***.***&gt;
Cc: He Zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [BigDataBiology/SemiBin] The issue of GTDB reference database (Issue #100)





 
@zh8008 does this answer your question? Please let us know if you need more info

**Comment by psj1997** [comment]
Yes. This is OK.

Sincerely
Shaojun
