### ISSUE TITLE
Small reference database or test taxonomy TSV file

### ISSUE THREAD

**Issue by bebatut** [BigDataBiology/SemiBin#102]
Hi,

I am creating a Galaxy wrapper for SemiBin ([current work](https://github.com/bebatut/tools-iuc/tree/semibin/tools/semibin)).

Thanks for having small test data there. It is so helpful to test the wrapper (specially with the max 1MB rules we have in Galaxy for test data)

I am struggling now with 2 things:
- The reference database is too big. Do you have a smaller reference database I could use?
- I did not find any test data for the taxonomy. Do you have one somewhere? 

Thanks for your help.

Bérénice

**Comment by psj1997** [comment]
Hi,

Thanks for your attention of SemiBin.

`The reference database is too big. Do you have a smaller reference database I could use?
How small do you mean? Because the reference database for this purpose is always very big.

Sincerely
Shaojun
`

**Comment by bebatut** [comment]
Hi,
I understand that the reference database is big in real world case. Here I meant for functional tests (using the input data you already put in the `test` folder) of `SemiBin generate_cannot_links`, `SemiBin single_easy_bin` and `SemiBin multi_easy_bin` commands.
If we do not have tests, we can not make SemiBin available via Galaxy.

Also, I try to test with taxonomy file, but I could not find a description of this file, how to create it, or an example. Do you have one?

Bérénice

**Comment by luispedro** [comment]
Thank you, Bérénice for your efforts

In SemiBin, you can also pass the results of the annotation directly to the tool. Originally, this was meant so that people who are annotating their contigs anyway as part of their pipeline could avoid doing it twice.

We can also generate this on our side and upload it. Would this work?

**Comment by bebatut** [comment]
> In SemiBin, you can also pass the results of the annotation directly to the tool

Do you mean the taxonomy file there?
Do you have an example of such file somewhere?

The idea there is to add small tests to guarantee a certain quality and stability of the Galaxy wrapper on the top of the tool (e.g. after updates). Usually the test data should be smaller than 1MB (your test datasets were really useful there, thanks!). Not really important if the results make sense, just testing that the generated outputs look okayish (structure, etc).

In the case of SemiBin, I created a [data manager](https://docs.galaxyproject.org/en/latest/dev/data_managers.html) to import the database and have the GTDB downloaded once in a server (as users do not have the access to that...).
But it means I can not use the big database to test the commands :disappointed_relieved:. I would need a small version of it...

**Comment by psj1997** [comment]
Sorry for the late reply.

There seems two ways to deal with it: 
(1) we provide the taxonomy file with your test contig and you can run with the taxonomy file (do not need the reference database);
 (2) You run with a very small reference database (< 1MB) and run the full pipeline (I am not sure if such a small reference database can work, I can try it). 

Which one do you think is better? 

Sincerely
Shaojun

**Comment by bebatut** [comment]
> Sorry for the late reply.

No worries. We are all busy or in holidays :smiley:

It would be awesome to have both ways (if possible). So I can test them both

**Comment by psj1997** [comment]
For (1), if you can provide me the test contig? So I can generate the taxonomy file for you.

For (2), I will try if we can get such a small reference database for SemiBin.

Sincerely
Shaojun

**Comment by bebatut** [comment]
For (1) I used the nice test data you have in there :smile:

**Comment by psj1997** [comment]
Do you mean this link: https://github.com/BigDataBiology/SemiBin_tutorial/tree/main/single_sample_binning?

Sincerely
Shaojun

**Comment by bebatut** [comment]
No that one: https://github.com/BigDataBiology/SemiBin/tree/main/test/single_sample_data

**Comment by psj1997** [comment]
Hi

I have generated a fake taxonomy file for the test data (https://drive.google.com/file/d/1f_FGQIsPdByrcSEiuJalWfWYOOr9NU1p/view?usp=sharing). 

You can run the commands with this file like these:

`SemiBin generate_cannot_links -i input.fasta -o single_output --taxonomy-annotation-table taxonomyResult.tsv`

`SemiBin single_easy_bin -i input.fasta -o single_output -b input.sorted.bam --taxonomy-annotation-table taxonomyResult.tsv`

`SemiBin multi_easy_bin -i input_multi.fasta -o multi_output -b *.bam --taxonomy-annotation-table taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv taxonomyResult.tsv -s : `

Sincerely
Shaojun

**Comment by bebatut** [comment]
Hi.

Thanks for the taxonomy file. I adapted it a bit but it works for `single_easy_bin` but not with `multi_easy_bin`: it raises an error `SemiBin: error: unrecognized arguments: ` if I give several taxonomy files.
Is it an expected behavior?

Best,

Bérénice

**Comment by psj1997** [comment]
Can you try the latest version of SemiBin from the github repo and install it from source? There are a bug for this with the anaconda version.

Sincerely
Shaojun

**Comment by bebatut** [comment]
I will try from the sources.
With Galaxy, I would need a conda version. Could you also create a new release?

**Comment by luispedro** [comment]
If it is possible for you to test it out from github, that would be great. If it does work, we'll be happy to do a conda release.

**Comment by bebatut** [comment]
It seems to work with sources from GitHub, but not with latest conda version

**Comment by luispedro** [comment]
Should we also include the test dataset in our repository and internal test suite? You'd also need it, right?

/cc @psj1997

**Comment by bebatut** [comment]
It would be awesome to have a test reference database too. 
I only miss that and the new conda package to finish the wrapper for Galaxy: https://github.com/galaxyproject/tools-iuc/pull/4690

**Comment by luispedro** [comment]
The conda version is now up to date

**Comment by luispedro** [comment]
If I understand correctly, this issue can now be closed, but let us know if anything more is needed

We will also be happy to link to the Galaxy wrapper from our documentation once that's available for users.

**Comment by bebatut** [comment]
Thanks @luispedro. I am currently testing with new conda package.

1 thing missing would be a small reference database to test not only the use of the taxonomy file. Would that be possible to create?

**Comment by psj1997** [comment]
Yes. This step is running mmseqs to get the taxonomy file and I guess it is hard for testing.

**Comment by bebatut** [comment]
On Galaxy side, it is not much to test SemiBin but the Galaxy wrapper itself, being sure everything is correctly connected / called, that the database is correctly called, etc
The results do not have to make sense, just having something :smile:

**Comment by psj1997** [comment]
OK. I can try if it is possible to generate a small reference genome to make SemiBin run.
