### ISSUE TITLE
About GPU-mode

### ISSUE THREAD

**Issue by joeyclancy** [BigDataBiology/SemiBin#105]
Hi SemiBin team,
  Thanks for the wonderful jobs, when I read your paper I couldn't wait to use it. I have noticed the SemiBin supports the GPU-mode, while I can not find the optional arguments about it when I run with single_easy_bin or other modes. When I processing the code with 'CUDA_VISIBLE_DEVICES=2 SemiBin     single_easy_bin     --input-fasta contigs.fa     -m 1000     --input-bam contigs.bam     --environment soil     --output output' in our GPU node, the output log is 'Setting number of CPUs to 28' seems it runs with CPU instead of GPU (all our CPUs were loaded).  I wonder how I can run SemiBin with GPU-mode in the correct way?

Sincerely
Joey

**Comment by psj1997** [comment]
Hi, joey

Thanks for your attention of SemiBin.

(1) You can specify this with --engine flag 

(2) When you run SemiBin with our pretrained model (--environment soil), SemiBin does not train the model, and it skips the GPU part. So it just needs CPU.

Sincerely
Shaojun

**Comment by joeyclancy** [comment]
Thanks for help, Shaojun

So is the GPU-mode just used for model tranining?

Sincerely
Joey

**Comment by psj1997** [comment]
Yes. Model training need GPU that can make it much faster.

Sincerely
Shaojun

**Comment by joeyclancy** [comment]
Thanks for your time, Shaojun. It would be very help.
