### ISSUE TITLE
Multi-sample binning: possibility to have reads mapping to the indivdual sample contigs?

### ISSUE THREAD

**Issue by bebatut** [BigDataBiology/SemiBin#107]
Hi,

I tried to run `SemiBin multi_easy` providing multiple BAM files, 1 per sample.
I found a bit confusing to have to do the reads mapping to the combined contig. 
For other tasks, we might already have the reads mapped to the contigs for each sample. Having to 1) concatenate the contigs and 2) map the reads of each sample against the concatenated contigs is adding tasks that need a lot of computational resources and might confuse users (or at least it should be more explicit in the usage documentation).

Would it be possible to give BAM files previously generated, with reads mapped to individual sample contigs?

Bérénice

**Comment by psj1997** [comment]
Hi,

The reason we use multi-sample binning is that we can use the abundance information across all samples and get better binning results. With reads mapped to individual sample contigs do not have these abundance information.

Sincerely
Shaojun
