### ISSUE TITLE
eukaryotic genomes

### ISSUE THREAD

**Issue by Thexiyang** [BigDataBiology/SemiBin#109]
Thanks for this nice tool! Does it also fit to bin eukaryotic genomes?

**Comment by psj1997** [comment]
Thanks for your attention to SemiBin. We do not test it to bin eukaryotic genomes now. But maybe you can bin with our pretrained model for trying. 

Sincerely
Shaojun

**Comment by luispedro** [comment]
@Thexiyang Thanks for reaching out. This is now listed as an [FAQ](https://semibin.readthedocs.io/en/latest/faq/#does-semibin-work-for-eukaryotic-genomes)

If you are willing to share data, we would be very happy to test out SemiBin for eukaryotes and help you bin your data. Feel free to get in touch through email (luispedro@big-data-biology.org or shaojun@big-data-biology.org).
