### ISSUE TITLE
Input error: Chromosome found in non-sequential lines. This suggests that the input file is not sorted correctly.

### ISSUE THREAD

**Issue by PeterCx** [BigDataBiology/SemiBin#111]
Hi there,

I keep encountering the following errors with the input file:

2022-09-16 08:03:58,832 - Do not detect GPU. Running with CPU.
2022-09-16 08:03:58,832 - Multi-sample binning.
2022-09-16 08:03:58,832 - Generate training data.
2022-09-16 08:11:58,173 - Calculating coverage for every sample.
2022-09-16 08:15:59,341 - Processing `MEGAHIT_Contigs/Bowtie_Output/10_before.sorted.bam`
Input error: Chromosome 10_day52:k141_182233 found in non-sequential lines. This suggests that the input file is not sorted correctly.
Input error: Chromosome ERR6929680:k141_1279881 found in non-sequential lines. This suggests that the input file is not sorted correctly.
etc etc etc

There is an issue with thousands of chromosomes.

I am using the easy multi samples binning mode with the following code:

`SemiBin multi_easy_bin -p 1 -i concatenated.fa -b *.sorted.bam -o SemiBin/ > SemiBin_Output`

The concatenated contig file was generated with the following code:

`SemiBin concatenate_fasta -i *.final.contigs.fa -o concatenated.fa `

I know a similar issue was opened here in the past and I have looked at it closely. I have followed https://semibin.readthedocs.io/en/latest/generate/ and I am sure the bam file is sorted correctly.

Your help is greatly appreciated.

Kind reagrds,

P

**Comment by psj1997** [comment]
Hi, 

It seems that it is still the issue caused by the bam file not sorted correctly. Can you try `samtools sort` and then run `bedtools genomecov -bga  -ibam MEGAHIT_Contigs/Bowtie_Output/10_before.sorted.bam` to check if bedtools can calculate the coverage successfully.

Sincerely
Shaojun

**Comment by PeterCx** [comment]
I can confirm it was a problem with the BAM file.

The SAM file was not created with the parameters specified here https://semibin.readthedocs.io/en/latest/generate/ in the first place. So it was doomed from the get go.

If you follow https://semibin.readthedocs.io/en/latest/generate/ exactly you will not encounter this problem. Apologies for re-opening this issue.

Kind regards,

Peter

**Comment by luispedro** [comment]
I will note that the generate page was improved yesterday as well, so that it's clearer now. We also now more consistently call the input files `.sorted.bam` in the docs, which should be more explicit.

**Comment by PeterCx** [comment]
That's great. Many thanks
