### ISSUE TITLE
Feature request: Supply gene prediction via external file

### ISSUE THREAD

**Issue by sjaenick** [BigDataBiology/SemiBin#113]
Hi,

In our assembly workflow, we already perform gene prediction (prodigal), so it would reduce SemiBin runtime
if we could feed e.g. the GTF file we already have from prodigal into SemiBin instead of predicting genes again
internally. Could you consider adding an option for that?

Thanks!

**Comment by psj1997** [comment]
Thanks for your attention for SemiBin.

SemiBin can support this to some extend. You can install hmmsearch, and run 
`hmmsearch --domtblout output/markers.hmmout --cut_tc  --cpu 8 marker.hmm contig.faa`.

Then you can run `SemiBin single_easy_bin -o output ...`. SemiBin will find the markers.hmmout and skip the gene prediction step.

Sincerely
Shaojun

**Comment by luispedro** [comment]
This is now implemented in the github version and will part of `v1.5`
