### ISSUE TITLE
GTDB config error

### ISSUE THREAD

**Issue by zpinocchio** [BigDataBiology/SemiBin#116]
Thanks for your work.

I want to use my downloaded GTDB database, it seem work.
But in running Mmseq2, it throw a error

Input taxonomy database "//mmseqs2-GTDB/GTDB" is missing files:
- //mmseqs2-GTDB/GTDB_mapping
- //mmseqs2-GTDB/GTDB_nodes.dmp
- //mmseqs2-GTDB/GTDB_names.dmp
- /e/mmseqs2-GTDB/GTDB_merged.dmp

these *dmp file I think it was NCBI taxanomy database, so how can i generate the  GTDB_mapping file

**Comment by psj1997** [comment]
Thanks for your attention of SemiBin.

You can use mmseqs to download the file:
`mmseqs databases GTDB gtdb tmp`.

Or you can find how the generate these file from mmseqs2's docs: https://mmseqs.com/latest/userguide.pdf

Sincerely
Shaojun

**Comment by zpinocchio** [comment]
Thanks!
