### ISSUE TITLE
document Advanced workflows section

### ISSUE THREAD

**Issue by zpinocchio** [BigDataBiology/SemiBin#117]
Your usage document seems something error.
At Advanced workflows, the step3 train.
train.csv  train_split.csv  file does not exist, should be data_split.csv and data.csv?

And then,  follow the document, one error throw:
error: the following arguments are required: --mode

Thanks for your work!

**Comment by psj1997** [comment]
Thanks for pointing this. 
Yes, the usage document is a little out of date.

The files are data.csv and data_split.csv and you need to add --mode single.

We have updated the docs: https://semibin.readthedocs.io/en/latest/usage/

Sincrerely
Shaojun
