### ISSUE TITLE
prefix naming

### ISSUE THREAD

**Issue by bartns** [BigDataBiology/SemiBin#119]
Hi, thanks for the work with this binner!

I have a small feature request, and that is to add a prefix option for the naming of the bins and maybe the other output files. 
When combining bins from multiple (independent) samples it would be nice to have the sample name already in the bin for example.
Or when using DAS Tool with multiple binners one could more easily see where the bin comes from in the name. 

Another thing is that I have downloaded a newer version of the mmseqs2 GTDB and called the file names GTDB_v207* took me a standard download to find why it was ignoring my files. Small addition in the documentation would help and maybe including more info on how to download a new version.

`mmseqs databases <name> <o:sequenceDB> <tmpDir> [options]`
should be for SemiBin something like
`mmseqs databases GTDB GTDB /tmp`

[https://github.com/soedinglab/mmseqs2/wiki#downloading-databases](https://github.com/soedinglab/mmseqs2/wiki#downloading-databases)

**Comment by luispedro** [comment]
The request related to naming the output files has been introduced: `--tag-outputs` (see https://semibin.readthedocs.io/en/latest/subcommands/)

We are moving towards privileging the self-supervised mode, which does not use the GTDB, by the way, by the way.

**Comment by bartns** [comment]
This is great, thanks!
Looking forward to more updates
