### ISSUE TITLE
mtrand.pyx

### ISSUE THREAD

**Issue by hildebra** [BigDataBiology/SemiBin#121]
Hey Luis et al,

thanks for the recent update to semibin, I think this is very interesting and I was keen to try it on 100's of assemblies. Sometimes it finishes without problems, but I frequently get the following error:

_2022-11-07 09:41:10 t384n13 SemiBin[76479] INFO Did not detect GPU, using CPU.
2022-11-07 09:46:13 t384n13 SemiBin[76479] INFO Generate training data.
2022-11-07 09:46:14 t384n13 SemiBin[76479] INFO Calculating coverage for every sample.
2022-11-07 09:46:14 t384n13 SemiBin[76479] INFO Processed:/nbi/local/ssd/51647277/P18E90/Bin35P182/tmp8du56li4/P18E7-smd.bam
2022-11-07 09:53:32 t384n13 SemiBin[76479] INFO Processed:/nbi/local/ssd/51647277/P18E90/Bin35P182/tmp8du56li4/P18E0-smd.bam
2022-11-07 09:53:54 t384n13 SemiBin[76479] INFO Processed:/nbi/local/ssd/51647277/P18E90/Bin35P182/tmp8du56li4/P18E90-smd.bam
2022-11-07 09:56:49 t384n13 SemiBin[76479] INFO Start training from one sample.
2022-11-07 09:56:50 t384n13 SemiBin[76479] INFO Training model...
  0%|          | 0/15 [00:00<?, ?it/s]2022-11-07 09:56:50 t384n13 SemiBin[76479] INFO Generate training data of 0:
  0%|          | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/hpc-home/hildebra/env/anac3/envs/MFF/bin/SemiBin", line 10, in <module>
    sys.exit(main())
  File "/hpc-home/hildebra/env/anac3/envs/MFF/lib/python3.8/site-packages/SemiBin/main.py", line 1240, in main
    single_easy_binning(
  File "/hpc-home/hildebra/env/anac3/envs/MFF/lib/python3.8/site-packages/SemiBin/main.py", line 1001, in single_easy_binning
    training(logger, None,
  File "/hpc-home/hildebra/env/anac3/envs/MFF/lib/python3.8/site-packages/SemiBin/main.py", line 870, in training
    model = train_self(output,
  File "/hpc-home/hildebra/env/anac3/envs/MFF/lib/python3.8/site-packages/SemiBin/self_supervised_model.py", line 85, in train_self
    indices1 = np.random.choice(data_length, size=n_samples)
  File "mtrand.pyx", line 894, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken_

The call was:
SemiBin single_easy_bin  --training-type self --reference-db-data-dir /ei/projects/8/88e80936-2a5d-4f4a-afab-6f74b374c765/data/DB//mmseqs2-GTDB/ --input-fasta /hpc-home/hildebra/grp/data/projects//AssmblGrp_P18/metag//scaffolds.fasta.filt -b /hpc-home/hildebra/grp/data/projects/P18E0//mapping/P18E0-smd.cram /hpc-home/hildebra/grp/data/projects/P18E7//mapping/P18E7-smd.cram /hpc-home/hildebra/grp/data/projects/P18E90//mapping/P18E90-smd.cram  --output /hpc-home/hildebra/grp/data/projects//AssmblGrp_P18/metag//Binning/SB/  --random-seed 555 --tmpdir $SLURM_LOCAL_SCRATCH/MATAFILER//P18E90/Bin35P182/ -p 8

Would this be related to our CPU configuration?
thanks,
Falk

**Comment by psj1997** [comment]
Thanks for your attention of SemiBin.

Can you check if data.csv (the k-mer and abundance features) is correctly generated for the samples that having error? It seems that this error is caused with the empty data file.

Sincerely
Shaojun

**Comment by hildebra** [comment]
Hey Shaojun,
indeed the data.csv appear to be empty (see attached)
[data.csv](https://github.com/BigDataBiology/SemiBin/files/9951805/data.csv)

**Comment by psj1997** [comment]
I think there are also some other .csv files. Can you also help to check these files are empty or not?

Sincerely
Shaojun

**Comment by hildebra** [comment]
There was the three cov.csv, indeed one of them was empty:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/19647604/200328414-aa064ab5-63de-4334-9705-640b205d496d.png">

**Comment by hildebra** [comment]
Could this be related to the input being .cram? I should have enough space on the tmpdir in theory, though..

**Comment by psj1997** [comment]
It seems there are two .cram files are accurately processed, and /home/hildebra/grp/data/projects/P18E7//mapping/P18E7-smd.cram has an error. Can you help to run it again or just run this file to see where is the problem? Thanks!

Sincerely
Shaojun

**Comment by hildebra** [comment]
Hey Shaojun,
the .crams seem to be ok, so now I just convert crams to bams before passing them to SemiBin, this is so far working.
I will close this issue and just work with this strategy, thanks for your prompt replies!
Falk

**Comment by luispedro** [comment]
Thanks Falk for the report

I am going to reopen because there is still something wrong with SemiBin that should be fixed because someone else will sooner or later stumble on this

**Comment by psj1997** [comment]
Thanks Falk!

SemiBin uses `samtools view -bS -@ 8 -T contig.fa sample.cram > sample.bam` to convert cram file to bam file.

Does it the reason for the error?

Sincerely
Shaojun

**Comment by philippbayer** [comment]
I'm running into exactly the same issue now as part of trying to update the ATLAS pipeline to SemiBin v1.3. I'm running my testing on HPC with Lustre FS and I'm having a hunch that some parts don't 'see' the data as it's being generated.

data.csv, data_split.csv and ARZ4.sorted.bam_0_data_cov.csv have been made and are all bigger than 0 (512 bytes, 97 MB, 1.4  Mb respectively). No cram file is made, it's an associated bam-file (2.5GB in size).

Command:

         SemiBin single_easy_bin  --input-fasta Cobinning/filtered_contigs/ARZ4.fasta  --input-bam Cobinning/mapping/ARZ4.sorted.bam  --output Cobinning/SemiBin/ARZ4/  --threads 20  --training-type=self  --minfasta-kbs 200   --max-node 1 --max-edges 200   2> logs/semibin/bin/ARZ4.log

Log: 

```

**Comment by luispedro** [comment]
I will add a bit more error checking so that some categories of issues could be caught earlier with a better error message, but if the filesystem is not updating the files, I am not sure what we can do.

**Comment by philippbayer** [comment]
Maybe `bed_p.wait()` should happen before `calculate_coverage()` is run? Otherwise with some luck calculate_coverage() starts before bedtools has finished and files have been written
 https://github.com/luispedro/SemiBin/blob/8f891a9cc905dab25b0d53183bb3459b5e91ba11/SemiBin/generate_coverage.py#L93-L102

**Comment by luispedro** [comment]
We just released version 2, which includes a more error checking in the coverage computation and better diagnostics; so I am closing this here, but please feel free to re-open if it still relevant. Probably at least the error messages will be different (hopefully more informative).
