### ISSUE TITLE
Feature request: TSV with mapping contigs -> bins

### ISSUE THREAD

**Issue by luispedro** [BigDataBiology/SemiBin#123]
From Twitter: https://twitter.com/AnttiKarkman/status/1603418182844293120

**Comment by karkman** [comment]
And if I can make another wish, the bin names should only contain numbers, letters and underscore. This way the file would be compatible with anvi'o and SemiBin output could be visualised and manually curated with anvi'o.

Thanks!

**Comment by luispedro** [comment]
Changing the output names may break people's existing pipelines and we try to keep backwards compatibility, but we might at some point call a new release `SemiBin2` and then we can upgrade these things.

**Comment by luispedro** [comment]
I am adding an argument `--tag-output` which can be used like:

```bash
SemiBin ... --tag-output=Anything
```

to make the output bin files be named in the form `Anything_123.fa`

This is often useful to add the sample name; but makes it anvi'o compatible. Because nobody was using `--tag-output` before, there is no risk of breaking anyone's code.

**Comment by luispedro** [comment]
I also added the TSV table
