### ISSUE TITLE
SemiBin2 released?

### ISSUE THREAD

**Issue by rdenise** [BigDataBiology/SemiBin#126]
Dear Author,

I recently came across the preprint of SemiBin2 and was interested in trying it out. However, I was unable to locate the release of version 2. Is this intentional, as the paper is still a preprint, or is there a specific reason for its unavailability?

Thank you for your time and efforts in creating this tool.

Best regards,

**Comment by psj1997** [comment]
Thanks for your attention of SemiBin.

For now, the latest version of SemiBin (V1.4.0) covers all new features in the SemiBin2 manuscript. We will release the SemiBin2 later.

Sincerely
Shaojun

**Comment by rdenise** [comment]
So if I understand correctly, the version 1.4 of the software is reportedly the same as the version 2. Can you clarify the reasoning behind the major release of version 2, and how it is able to perform better than version 1 (if I look at the preprint) if they are identical in functionality?

**Comment by psj1997** [comment]
_So if I understand correctly, the version 1.4 of the software is reportedly the same as the version 2._

Yes. SemiBin1.4 is the SemiBin2 in the preprint. We will releae it as SemiBin2 later. 

_Can you clarify the reasoning behind the major release of version 2, and how it is able to perform better than version 1 (if I look at the preprint) if they are identical in functionality?_

The main difference of SemiBin2 compared to SemiBin1 is the self-supervised learning (https://github.com/BigDataBiology/SemiBin/commit/b13eb0b956193cb959597bb4b671266781252c5d) and the clustering algorithm for long read (https://github.com/BigDataBiology/SemiBin/commit/40af917dd0bed5bf2f0ca79ff6181cf7df004cc6).

Sincerely
Shaojun

**Comment by rdenise** [comment]
Thank you for the clarification. Because I was as you could see confuse that version 1.4 and version 2 are in fact the same one.

Best
Remi
