### ISSUE TITLE
GPU utilization

### ISSUE THREAD

**Issue by strejcem** [BigDataBiology/SemiBin#127]
Hi,
I've spend some time playing around with SemiBin and so far I really like it. I have a RTX 3060 with 12GB VRAM and I see that during the self-training the GPU utilization peaks at 25% and only 1GB of VRAM is being used. Is there any reason that the GPU is not fully utilized?

Thanks!

Michal

**Comment by luispedro** [comment]
This is hard to debug. Pytorch2 (which is coming out later in the year) may help, but from our side I am not sure if much can be done.

**Comment by psj1997** [comment]
Hi, can you provide me the log information to check which step takes much time?

Sincerely
Shaojun

**Comment by strejcem** [comment]
Eh, does SemiBin produce any logs with default multi_easy_bin subcommand? I couldn't find any and I already closed the session. Anyway, I was checking the times that individual steps took. I got 4 metagenomes that I did individual assembly and then concatenated them together and ran BWA to get the sorted bams and finally run the SemiBin multi_easy_bin. For the first sample the self-training took about 8mins and then the binning took 18hrs. The subsequent 3 samples also took around 8mins to self-train but the binning was much faster, about 5-10mins per sample iirc.

What kind of log do you need? I can rerun it.

**Comment by strejcem** [comment]
In terms of reads, they are about the same 11Gbp the first one and the rest are around 14Gpb.  In terms of assembly, the first one is 200Mbp, the second is 130Mbp, and the third and fourth are 220Gbp.

I started another run with a different assembler and this time the training of the first sample took the same 8mins but the binning was done in 6min. However the second sample is now running already for the 15hrs and has not finished. The step that takes a lot of time is 'INFO Start binning."

**Comment by strejcem** [comment]
The second run has finished. It was overall slightly faster but generally the same amount of time. This time the second sample (B) was the longest one and the others were quite fast. 

Here is the copied terminal [log.txt](https://github.com/BigDataBiology/SemiBin/files/10540583/log.txt)

**Comment by luispedro** [comment]
Motivated by this discussion, going forward, SemiBin will always save its logs alongside the inputs, so it is easier to debug later: https://github.com/BigDataBiology/SemiBin/commit/091d85fb7b0928a2d90cedf4dda872e478cc30a7
