### ISSUE TITLE
Error running single_easy_bin on coassembly

### ISSUE THREAD

**Issue by heleeno** [BigDataBiology/SemiBin#129]
Hi,

I'm trying to run SemiBin on my coassembly running: 
SemiBin single_easy_bin -r /scratch2/heleen --input-fasta concatenated.fa --input-bam bm1_HMG01_BF_1_sorted.bam --output SemiBin_single_easy_bin_GTDB_location

It has been running until downloading GTDB but after that it is running into problems. It is not clear to me what the problem is. In the end it gives an error stating that something is wrong with a specific contig but I don't see why? It would make me very happy if you could have a look to see what the problem is. I attached the outputfile. See output file here: [output.txt](https://github.com/BigDataBiology/SemiBin/files/10765131/output.txt)

Many thanks in advance! Heleen

**Comment by psj1997** [comment]
Sorry for the late reply. It seems that this type of name: 'asm_megahit_ctgs_fmt_mins1000:contig_280762' is used in multi_sample binning. Can you show me what the data.csv is?

Sincerely
Shaojun

**Comment by luispedro** [comment]
@heleeno : do you have any updates? Otherwise, we will close this issue.
