### ISSUE TITLE
Failing to index concatenated fasta

### ISSUE THREAD

**Issue by x-rv** [BigDataBiology/SemiBin#130]
I concatenated assemblies from 66 samples with `SemiBin concatenate_fasta --input-fasta ~/xrey/assemblies_remei/* --output concatenated.fa.d`. The output is a 198GB concatenated.fa for which I tried to build an index with 3 different programs (BBmap, BWA and BowTie2), but all of them crash due to not having enough memory. I have assigned up to 750Gb memory for the process but it's not enough. For the record, the commands I used to build the index are these:

With BBmap:
`bbmap.sh -Xmx700g ref=../concatenate/concatenated.fa.d/concatenated.fa`
With BWA:
`bwa index ../concatenate/concatenated.fa.d/concatenated.fa `
With BowTie2:
`bowtie2-build --large-index ../concatenate/concatenated.fa.d/concatenated.fa indexed.fa`

Any idea of how should I proceed? Might I have done something strange when concatenating the FASTA?

**Comment by psj1997** [comment]
Hi, sorry for the late reply.

I guess the reason is that the concatenated.fa is very big. Maybe you can try SemiBin concatenate_fasta --input-fasta ~/xrey/assemblies_remei/* --output concatenated.fa.d -m 2000 to remove some short seqs.

Sincerely
Shaojun
