### ISSUE TITLE
abundance analysis of bin

### ISSUE THREAD

**Issue by nashanghenzan** [BigDataBiology/SemiBin#132]
hi, recently i found that i can't use quant_bin function of metawrap due to the memory limit of my computer, i find that the semibin also output some tables that show contigs coverage info. so can just use mean contigs cov of bins to assign abundance of bins in samples/bams?that's important for me. thank you

**Comment by psj1997** [comment]
If you run multi_sample_binning, the output coverage value has been changed by some normalization. If you want this, maybe you can run 'bedtools genomecov' again.

Sincerely
Shaojun

**Comment by nashanghenzan** [comment]
> If you run multi_sample_binning, the output coverage value has been changed by some normalization. If you want this, maybe you can run 'bedtools genomecov' again.
> 
> Sincerely Shaojun

thank you very much
