### ISSUE TITLE
Error: SemiBin concatenate_fasta

### ISSUE THREAD

**Issue by FelipeMSD** [BigDataBiology/SemiBin#143]
Dear Luis,

I am developing a Nextflow pipeline to help me with the generation of bins using SemiBin2 multi_easy_bin, however, when I run the command line:

`SemiBin concatenate_fasta -i ${assemblies}*.fa -o concatenated` with container `'quay.io/biocontainers/semibin:1.5.1--pyhdfd78af_0'` it seems the concatenation is done but the pipeline is interrupted by the error:

`Error: the header of the contig 'sample_name:k141_836210' contains the separator (':'), please choose another separator.`. Why do you think this might be happenning? It does not happen when I run it as a bash script...

Kind regards,
Felipe

**Comment by luispedro** [comment]
You are sure that none of the inputs contains an ID with the separator? Maybe you are inadvertently attempting to re-concatenate the outputs of a previously `concatenate_fasta` call?

(The error message would be more helpful if it also included the exact filename where the issue was seen; I'll add that)

**Comment by FelipeMSD** [comment]
That’s true. Let me check this. Thank you!

On 30 Aug 2023, at 10:14, Luis Pedro Coelho ***@***.******@***.***>> wrote:



You are sure that none of the inputs contains an ID with the separator? Maybe you are inadvertently attempting to re-concatenate the outputs of a previously concatenate_fasta call?

(The error message would be more helpful if it also included the exact filename where the issue was seen; I'll add that)

**Comment by FelipeMSD** [comment]
You were right. My mistake... Thank you very much!

**Comment by luispedro** [comment]
No problem and the report did result in a small improvement to `SemiBin`: the next person to face the same issue will have a slightly easier time figuring it out as the error message will be more specific
