### ISSUE TITLE
Multi-sample approach and bowtie2-build

### ISSUE THREAD

**Issue by FelipeMSD** [BigDataBiology/SemiBin#144]
Dear Luis,

I'm testing both the single-sample and the multi-sample approaches with SemiBin2 (according to your instructions here: https://github.com/BigDataBiology/SemiBin_tutorial_from_scratch), however, as bowtie2-build does not work with multiple cores and I'm working with a  >100G concatenated.fasta file, bowtie2 is taking a lot of time to build the index and I'm afraid I don't have a very high limit of hours for that. Do you have any tip on how to cope with this? Any other tools you would use instead to make the .bam files?

Kind regards,
Felipe

**Comment by FelipeMSD** [comment]
I just saw here: https://github.com/BenLangmead/bowtie2/issues/36 that they fixed it for newer versions and it seems to be working now. Cheers

**Comment by FelipeMSD** [comment]
In fact, now I'm having this problem:

`Command executed:

  bowtie2-build --threads 12 -f concatenated/concatenated.fa multiple_index

Command exit status:
  1

Command output:
    Ran out of memory; automatically trying more memory-economical parameters.
  Using parameters --bmax 2172 --dcv 4096
  
  Command error:
  Building a LARGE index
  Could not allocate space for a joined string of 137967960681 elements.
  Switching to a packed string representation.
  Building a LARGE index
  Could not find approrpiate bmax/dcv settings for building this index.
  Already tried a packed string representation.
  Please try indexing this reference on a computer with more memory.`

So I'm afraid I won't be able to test the multiple-sample approach if I'm not able to build the large bowtie2 index. Is there an alternative for this?

**Comment by psj1997** [comment]
Hi

Thanks for your attention of SemiBin.

If you have tried to remove the short contigs from the concatenated.fasta? For example, contig smaller than 2500bp.

Sincerely
Shaojun

**Comment by FelipeMSD** [comment]
Not yet. Let me try it. Thanks

**Comment by FelipeMSD** [comment]
Dear Shaojun,

Even after removing these contigs the fasta file Is still so big (~60G) that the time and memory requirements for bowtie2-build are unfeasible... The job keeps been killed

**Comment by psj1997** [comment]
If it needs too much memory,you can try to map all samples to the contig from one sample (It will take more time, but it will work).

Sincerely
Shaojun

**Comment by FelipeMSD** [comment]
But then for SemiBin2 multi_easy_bin what do you use?

**Comment by FelipeMSD** [comment]
But isn't it different than using multi_easy_bin? I think I'm still having problems to see here how the outcome will be the same because, if I understood it right, the idea will be to map all fastq pairs to all assemblies and then run single_easy_bin for each combination, right? Here: https://www.nature.com/articles/s41592-023-01934-8, they at least concatenate the coverage of all mapping done between the same fastq pairs and all assemblies before binning with metabat2. Should I include a step here that does a similar thing for semibin2?

**Comment by psj1997** [comment]
_But isn't it different than using multi_easy_bin? I think I'm still having problems to see here how the outcome will be the same because, if I understood it right, the idea will be to map all fastq pairs to all assemblies and then run single_easy_bin for each combination, right?_

The only difference compared to multi_easy_bin is that the value of coverage features will be different (because the different ways to map reads).

Sincerely
Shaojun
