### ISSUE TITLE
Replicability of semibin2 single_easy_bin

### ISSUE THREAD

**Issue by FelipeMSD** [BigDataBiology/SemiBin#145]
Dear all,

I ran SemiBin2 single_easy_bin twice on the fasta/bam files and while I obtained 18 bins on the first run I hade only 15 bins on the second one. Is it expected?

**Comment by psj1997** [comment]
Yes. If you want to make the results same, you can set the `--random-seed` parameter.

Sincerely
Shaojun

**Comment by FelipeMSD** [comment]
Super! Thank you!
