### ISSUE TITLE
Add option to bypass coverage calculation

### ISSUE THREAD

**Issue by fplaza** [BigDataBiology/SemiBin#148]
Hi,

I am using SemiBin on a GPU cluster where I have a limited time quota.
Would it be possible to add a parameter so I can calculate contig coverages on CPU nodes only, and use my credits more efficiently?

Thanks,
Florian

**Comment by psj1997** [comment]
Hi,

My suggestion is you can use `generate_sequence_features_single` or `generate_sequence_features_multi` to generate the features on CPU node, then running training on GPU node, finally running `bin` on CPU node.

Sincerely
Shaojun

**Comment by fplaza** [comment]
Thanks for suggestion @psj1997 . I will give it a try.
What about detection of single copy marker genes?
On the nodes I am using, it can take up to 30 minutes with large assemblies.

**Comment by psj1997** [comment]
Which version of SemiBin you have used?

**Comment by fplaza** [comment]
The latest version on conda (2.0.2), with the self-supervised mode

**Comment by psj1997** [comment]
Do you have changed the `orf-finder` parameter? By default, I think SemiBin2 is using `fast-naive` which is the fastest.

Sincerely
Shaojun

**Comment by fplaza** [comment]
I have been using the SemiBin entry point (default = prodigal) instead of SemiBin2 (default = fast-naive) which explain why it has been so slow.
Is the hmmer running time negligible compared to orf finding?
Regardless, doesn't it make sense to compute the hmmer.out file with the generate_sequence_features command?

**Comment by psj1997** [comment]
I think orf finding takes more time.

`Regardless, doesn't it make sense to compute the hmmer.out file with the generate_sequence_features command?`
I think it doesn't matter when doing this in generate_sequence_features or binning, they can all be runned in CPU node.

**Comment by fplaza** [comment]
So your recommendation is:
generate_sequence_features_single -> CPU node
train -> GPU node
bin-> CPU node

Thank again for you help.

**Comment by luispedro** [comment]
The next version of SemiBin will produce a warning if you call `SemiBin` instead of `SemiBin2`, which will hopefully be helpful to avoid using outdated approaches
