### ISSUE TITLE
Empty data.csv file and IndexError with SemiBin2

### ISSUE THREAD

**Issue by AAwan2** [BigDataBiology/SemiBin#154]
[SemiBinRun.log](https://github.com/BigDataBiology/SemiBin/files/14346881/SemiBinRun.log)

**Command used:** 

SemiBin2 single_easy_bin -i /workspace/aawan2/Final_Assemblies/WT_Chow/final.contigs.fa -b /workspace/aawan2/mapped_out/All_Samples_Mapped_WT_Chow/*sorted.bam -o output

**Error (data coverage was calculated but data.csv was empty):** 

2024-02-20 01:08:27 kleinerserver2.cals.ncsu.edu SemiBin[2955434] INFO Start training from one sample.
2024-02-20 01:08:27 kleinerserver2.cals.ncsu.edu SemiBin[2955434] INFO Training model...

  0%|          | 0/15 [00:00<?, ?it/s]2024-02-20 01:08:27 kleinerserver2.cals.ncsu.edu SemiBin[2955434] INFO Generate training data of 0:

  0%|          | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/tools/Miniconda3/envs/semibin/bin/SemiBin2", line 10, in <module>
    sys.exit(main2())
             ^^^^^^^
  File "/tools/Miniconda3/envs/semibin/lib/python3.12/site-packages/SemiBin/main.py", line 1481, in main2
    single_easy_binning(
  File "/tools/Miniconda3/envs/semibin/lib/python3.12/site-packages/SemiBin/main.py", line 1170, in single_easy_binning
    training(logger, None,
  File "/tools/Miniconda3/envs/semibin/lib/python3.12/site-packages/SemiBin/main.py", line 1018, in training
    model = train_self(output,
            ^^^^^^^^^^^^^^^^^^
  File "/tools/Miniconda3/envs/semibin/lib/python3.12/site-packages/SemiBin/self_supervised_model.py", line 74, in train_self
    train_data_depth = train_data_input[:, 136:len(data.values[0])]
                                                   ~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by psj1997** [comment]
Hi

Can you have a look of other files that SemiBin2 generate? The size of data.csv, cov.csv and cov_split.csv. Thanks!

Sincerely
Shaojun

**Comment by AAwan2** [comment]
Thank you for the response! Yes, the data.csv and data_split.csv are 4kb. They have headers but no other information. The cov_split.csv files are ~1-3MB and have the appropriate information. I am attaching the relevant files. Thanks for your help again!
[data_split.csv](https://github.com/BigDataBiology/SemiBin/files/14387275/data_split.csv)
[data.csv](https://github.com/BigDataBiology/SemiBin/files/14387279/data.csv)

[MUC2_IN_53_S37_WT_Chow_sorted.bam_26_data_split_cov.csv](https://github.com/BigDataBiology/SemiBin/files/14387284/MUC2_IN_53_S37_WT_Chow_sorted.bam_26_data_split_cov.csv)

**Comment by psj1997** [comment]
Hi, 

I think the reason is that SemiBin calculate the k-mer features using the first word of the fasta hearder `k141_18491`, which can not match `k141_18491 flag=1 multi=9.0000 len=6321_1` from mapping.

From my side, I think a good solution is remove the ` flag=1 multi=9.0000 len=6321` part from the contig file and rerun the mapping and binning. 

Sincerely
Shaojun

**Comment by luispedro** [comment]
Thanks @AAwan2 for the report. Out of curiosity, how are you generating the BAM files? I would expect most tools to have cut the header past the first space character

**Comment by AAwan2** [comment]
@psj1997 Thanks for the help! I will remove the headers and try again.

@luispedro I used bbmap in semiperfect mode for the mapping.

**Comment by AAwan2** [comment]
Thank you so much both. It worked with the reformatted headers.
