### ISSUE TITLE
Some clarification about the data.csv and data_split.csv content

### ISSUE THREAD

**Issue by kafker** [BigDataBiology/SemiBin#157]
Dear Devs,

Thank you for providing a binning tool tuned for long-read assemblies.

Understanding the content of most intermediate files generated from the following command was pretty straightforward to me:

`SemiBin2 single_easy_bin --sequencing-type=long_read --input-fasta AD/assembly.fasta --input-bam alm.bam --output output`

However, I don't get the meaning of the numerical values reported in data.csv and data_split.csv.  I know data.csv and data_split.csv are used to generate a new model

Thank you

**Comment by luispedro** [comment]
Dear @kafker,

I'm glad you are getting benefits from SemiBin.

I'm going to ask whether you would be willing to repost this to the user mailing-list as it is not really an "Issue" in the sense of a bug with the software (or even the documentation). See https://groups.google.com/g/semibin-users

The files `data.csv` contain the features (the 4-mer frequencies of each contig and the estimated abundances).

HTH, Luis
