### ISSUE TITLE
Accept CRAM files instead of BAM

### ISSUE THREAD

**Issue by fplaza** [BigDataBiology/SemiBin#158]
Hi,

I was wondering if you could implement a feature to accept CRAM files instead of BAM.
It seems that bedtools coverage does not accept this format but its works with samtools depth.

Best,
Florian

**Comment by luispedro** [comment]
SemiBin does accept CRAM instead of BAM, but it's implemented by expanding CRAM to BAM in a temporary file

**Comment by fplaza** [comment]
Not sure it is very efficient when SemiBin is I/O bound.  Have you considered using samtools depth that handles them natively?
Anyway, I saw that the aemb module is now available in stobealign. Do you plan to release a new version of SemiBin that uses it soon?

**Comment by luispedro** [comment]
IIRC `samtools depth` was slower for BAMs, but it's been a long time since we looked at that.

Yes, a new version of SemiBin which will take the output of strobealing-aemb is going to be released soon (I was literally working on that rn)
