### ISSUE TITLE
bam files from bowtie2 or strobealign 

### ISSUE THREAD

**Issue by microsud** [BigDataBiology/SemiBin#161]
Thanks for this impressive binning tool, extensive documentation, and software support.

I was wondering if the bam file created using the semibin2 documentation approach or strobealign approach has critical implications on the binning algorithm?

```
bowtie2-build -f contig.fa contig.fa 

bowtie2 -q --fr -x contig.fa -1 reads_1.fq.gz -2 reads_2.fq.gz -S contig.sam -p 4  
samtools view -h -b -S contig.sam -o contig.bam  
samtools view -b -F 4 contig.bam -o contig.mapped.bam  
samtools sort contig.mapped.bam -o contig.mapped.sorted.bam  
samtools index contig.mapped.sorted.bam
```

Or 

``` 
strobealign -t 8 ref.fa reads.1.fastq.gz reads.2.fastq.gz | samtools sort -o sorted.bam
```

Looking forward to your feedback.

Best wishes,
Sudarshan

**Comment by psj1997** [comment]
I think there will be no big influence.

**Comment by microsud** [comment]
Thanks for the swift response :)
