### ISSUE TITLE
Only 2 contigs contain 1000 basepairs

### ISSUE THREAD

**Issue by timternetnet** [BigDataBiology/SemiBin#163]
Hi!
A sample with BAM file for which the assembly has 2 contigs (generated with Flye using Nanopore long read data) throws the following error:
```
ERROR: There are 2 contigs in input file medaka_consensus/consensus.fasta, but only 2 contain(s) at least 1000 basepairs.
```
Metabat2 doesn't have an issue with this dataset, and the error doesn't make a lot of sense to me... does anyone know what went wrong?
Thanks!

**Comment by luispedro** [comment]
Hi @timternetnet, we had set a minimum number of contigs as we didn't think that it would be meaningful to bin such a small number. Effectively, either the two contigs are in the same bin or they are not, right?

**Comment by timternetnet** [comment]
Ah well I assumed it would predict this for me. Mainly useful to deal with identical output formats when looping over a lot of samples, and the coverage stats are now also missing. But no worries, it makes sense :). Thanks!

**Comment by luispedro** [comment]
I get that. I think that there were other parts of the code in SemiBin that will error out if there are very few contigs as the code assumes that there are more contigs that that, so we ended up with this explicit error.
