### ISSUE TITLE
DAS Tool

### ISSUE THREAD

**Issue by francesco-ricci** [BigDataBiology/SemiBin#176]
Hello

can I run DAS Tool on SemiBin2 bins? Is there a scaffold2bin.tsv file?

Many thanks

**Comment by luispedro** [comment]
If I am guessing correctly about what was meant with the `scaffold2bin.tsv` file, SemiBin produces a file called `contig_bins.tsv` which assigns each contig a bin ID (including a pseudo-bin called `-1` for unbinned contigs)

You may find more help by posting on the [mailing-list](https://groups.google.com/g/semibin-users) as there may be other users with similar pipelines.

**Comment by francesco-ricci** [comment]
Thank you very much Luis
