### ISSUE TITLE
`single_easy_bin` unrecognized arguments: `-b` 

### ISSUE THREAD

**Issue by housw** [BigDataBiology/SemiBin#27]
Hi, 

it seems the `-b` argument hasn't been properly handled yet, here is the error message I got while running `single_easy_bin`: 
```
SemiBin: error: unrecognized arguments: -b 
```

Thanks, 
Shengwei

**Comment by psj1997** [comment]
Thanks!

Sorry, it is an oversight we made when recent updates. We have fixed it.

Sincerley
Shaojun
