### ISSUE TITLE
SemiBin doesn't download GTDB database

### ISSUE THREAD

**Issue by SilasK** [BigDataBiology/SemiBin#31]
Hello, 

I try to download the database for semibin, the log says it does download it but then the files are missing. 

I installed v0.2 with conda and run ( I specified version 0.2 not semibin=0.2=pyh5e36f6f_1)

`SemiBin download_GTDB --reference-db /abs/pth/databases/SemiBin_GTDB`

I got the log
```
2021-07-27 10:25:38,589 - Downloading GTDB.  It will take a while..
2021-07-27 10:30:05,012 - Download finished. Checking MD5...
````

But then the folder is missing. I use a normal linux server with shared filesystem. 

I get some mmseq files in the folder `/abs/pth/databases` but the timestamp is old. so I think they are not related.

**Comment by SilasK** [comment]
This makes sense if I check https://github.com/BigDataBiology/SemiBin/blob/a6164d7067d57b3e6a7cd020573b86aea3b72a86/SemiBin/utils.py#L299

**Comment by psj1997** [comment]
Hi

Thanks for the bug report.

Can you show me what you get in the `/abs/pth/databases`?

**Comment by SilasK** [comment]
```
-rw-r--r--  1 kiesers unige  32G Mar 17 06:28 GTDB
-rw-r--r--  1 kiesers unige    4 Mar 17 06:28 GTDB.dbtype
-rw-r--r--  1 kiesers unige  13G Mar 17 06:23 GTDB_h
-rw-r--r--  1 kiesers unige    4 Mar 17 06:24 GTDB_h.dbtype
-rw-r--r--  1 kiesers unige 2.4G Mar 17 06:31 GTDB_h.index
-rw-r--r--  1 kiesers unige 2.5G Mar 17 06:30 GTDB.index
-rw-r--r--  1 kiesers unige 3.4G Mar 17 06:33 GTDB.lookup
-rw-r--r--  1 kiesers unige 1.5G Mar 17 06:35 GTDB_mapping
-rw-r--r--  1 kiesers unige 769K Mar 17 06:22 GTDB.source
-rw-r--r--  1 kiesers unige 9.6M Mar 17 06:33 GTDB_taxonomy
drwxr-xr-x 11 kiesers unige   11 May 22 08:58 GTDB_V06
-rw-r--r--  1 kiesers unige   28 Mar 17 04:33 GTDB.version
drwxr-xr-x  2 kiesers unige    1 Jan 19  2021 host_genome
drwxr-xr-x 32 kiesers unige   61 May 16 08:02 old_conda_envs
-rw-r--r--  1 kiesers unige 5.5K Dec 13  2019 phiX174_virus.fa
```

**Comment by SilasK** [comment]
I put other datbases, e.g. the GTDB already in the same folder. So I'm not sure if these files come from semibin or not.

**Comment by psj1997** [comment]
Yes, there are from the SemiBin. 
There is a bug here. We assumed the input is something like /abs/pth/databases/SemiBin_GTDB/GTDB, so we use GTDB_dir = os.path.split(GTDB_path)[0] and GTDB will be downloaded to /abs/pth/databases/SemiBin_GTDB. 
Actually this is not good and we will fix it.
But you can use SemiBin train with the GTDB path: /abs/pth/databases/GTDB/ now.

Sincerely
Shaojun

**Comment by SilasK** [comment]
It seems to me that the naming of the `cannot` file is also not logical. e.g. I put in `cannot_bin.tsv` and the tool produced `cannot/cannot_bin.tsv.txt`

**Comment by psj1997** [comment]
This parameter wants an input like `cannot_bin`. We use this parameter to specify the cannot-link from one sample, so you can input the `sample_name`. Or you can just use the default, it will generate `cannot.txt`.

Sincerely
Shaojun
