### ISSUE TITLE
it's useless to set -p --processes --threads -t 

### ISSUE THREAD

**Issue by SiNoWu** [BigDataBiology/SemiBin#34]
mmseqs will use all CPU-cores by default
and for training ,the same issue

**Comment by psj1997** [comment]
Thanks! We have fixed this issue.

Sincerely
Shaojun

**Comment by SiNoWu** [comment]
> Thanks! We have fixed this issue.
> 
> Sincerely
> Shaojun

Sorry about that.
You have added a parameter 'num_process' in def predict_taxonomy().
But in single_easy_binning() and multi_easy_binning(), when running predict_taxonomy(), there isn‘t the parameter 'num_process'

**Comment by psj1997** [comment]
Thanks! Have fixed that.

Shaojun

**Comment by luispedro** [comment]
This is still the case for calling `kneighbors_graph` 

https://github.com/BigDataBiology/SemiBin/blob/81e6a57b9864d935282041373dbbaa043911da85/SemiBin/cluster.py#L36

https://github.com/BigDataBiology/SemiBin/blob/81e6a57b9864d935282041373dbbaa043911da85/SemiBin/cluster.py#L42

**Comment by psj1997** [comment]
I changed n_jobs = -1 to n_jobs = num_process.

Shaojun
