### ISSUE TITLE
An error of Pytorch dataloader:  RuntimeError: DataLoader worker (pid xxx) is killed by signal: Segmentation fault

### ISSUE THREAD

**Issue by SiNoWu** [BigDataBiology/SemiBin#35]
when trainning model with pytorch

I get a error：
RuntimeError: DataLoader worker (pid xxx) is killed by signal: Segmentation fault

I've searched this error，maybe it caused by setting num_workers > 0   in 

train_loader_unlabeled = DataLoader(
        dataset=dataset_unlabeled,
        batch_size=batchsize,
        shuffle=True,
        num_workers=16)

python version:3.9.6
torch version:1.8.0

according to  https://github.com/pytorch/pytorch/issues/4969

**Comment by psj1997** [comment]
Thanks! I know that DataLoader with num_workers > 0 may lead to an issue. But I do not get this error. Can you try to set num_workers = 0 to see if it will fix your issue? 

Thanks
Shaojun

**Comment by psj1997** [comment]
If it works, I can change to num_workers = 0.

**Comment by SiNoWu** [comment]
> If it works, I can change to num_workers = 0.

yes，it works

**Comment by SiNoWu** [comment]
> If it works, I can change to num_workers = 0.

Another issue ：
In cluster.py ,when running kneighbors_graph() , I don’t know the parameter ‘n_jobs=-1’
I don't find this parameter in kneighbors_graph, and this caused an error :
                 BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

**Comment by SiNoWu** [comment]
I just remove the n_jobs=-1,it works Ok now 
Binning is finished and I get my bins finally.
Best wishes for you and your project

**Comment by psj1997** [comment]
Thanks!

I am not very sure it is a common issue about Sklearn or BLAS. 
Maybe you can fix this by removing n_jobs = -1 or by https://github.com/scikit-learn/scikit-learn/issues/20539.

I will keep this and see if others also have this issue(I do not meet this error on some different machines).

Shaojun
