### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.

### ISSUE THREAD

**Issue by ZarulHanifah** [BigDataBiology/SemiBin#36]
Hello SemiBin maintainers,

I am running SemiBin coassembly mode as below. 

```
rule semibin_binning_coassembly:
        input:
                assem = rules.medaka_polish_coassembly.output,
                bam = lambda wildcards: expand(rules.map_reads_to_coassembly.output, source = wildcards.source, sample = get_samples_given_source(wildcards.source)),
                semibin_db = config["semibin_db"]
        output:
                directory("results/binning/coassembly/semibin/{source}")
        conda:
                "../envs/semibin.yaml"
        threads: 12
        shell:
                """
                SemiBin single_easy_bin -i {input.assem} -b {input.bam} -r {input.semibin_db} -o {output}
                """
```

I used conda to install semibin:

```
name: semibin
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.7
 - semibin=0.2=pyh5e36f6f_1
```

But the job exited prematurely. I am attaching the slurm error and output files.

In the slurm output, it says somethig about libmkl.

Thank you.
[semibin_binning_coassembly.source=riverine.err.txt](https://github.com/BigDataBiology/SemiBin/files/6987600/semibin_binning_coassembly.source.riverine.err.txt)
[semibin_binning_coassembly.source=riverine.out.txt](https://github.com/BigDataBiology/SemiBin/files/6987601/semibin_binning_coassembly.source.riverine.out.txt)

**Comment by psj1997** [comment]
Hi, it seems that it has an issue of pytorch. Can you try our latest SemiBin 0.3 to see if this issue still had? You can just use Semibin train  command to see if the training process is normal.

Shaojun

**Comment by ZarulHanifah** [comment]
Hello Shaojun,

Thank you for the reply. I can confirm now that it is working wonderfully. Thank you.
