### ISSUE TITLE
GTDB or mmseqs2 db confusion

### ISSUE THREAD

**Issue by ZarulHanifah** [BigDataBiology/SemiBin#37]
Hello Shaojun,

I am a bit confused.. Before using SemiBin, I have used GTDB and mmseqs2 before, and I have downloaded their db. The GTDB db was from [release202](https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz), here are the contents of the folder
```
fastani
manifest.tsv
markers
masks
metadata
mrca_red
msa
pplacer
radii
taxonomy
```

For mmseqs2 db, I downloaded the UniProtKB-TrEMBL version; here are the contents of the folder

```
UniProtKB-TrEMBL
UniProtKB-TrEMBL.dbtype
UniProtKB-TrEMBL_h
UniProtKB-TrEMBL_h.dbtype
UniProtKB-TrEMBL_h.index
UniProtKB-TrEMBL.index
UniProtKB-TrEMBL.lookup
UniProtKB-TrEMBL_mapping
UniProtKB-TrEMBL.source
UniProtKB-TrEMBL_taxonomy
UniProtKB-TrEMBL.version
```

I want to use SemiBin single_easy_bin without having to download another db. However, when I use the GTDB db, it cannot find the files like _taxonomy, names.dmp and nodes.dmp. It looked more like mmseqs2 db files. I also downloaded SemiBin db, and it looked like mmseqs2 db.

```
GTDB
GTDB.dbtype
GTDB_h
GTDB_h.dbtype
GTDB_h.index
GTDB.index
GTDB.lookup
GTDB_mapping
GTDB.source
GTDB_taxonomy
GTDB.version
```

Does this mean the db required for SemiBin is actually mmseqs2 db instead of GTDB?

**Comment by psj1997** [comment]
Yes. For the database files used in the annotation, we used mmseqs2 GTDB db.

**Comment by ZarulHanifah** [comment]
Thank you for the clarification.
