### ISSUE TITLE
Missing DB files

### ISSUE THREAD

**Issue by wisnu-adi** [BigDataBiology/SemiBin#38]
Hi there,

When I ran SemiBin single_easy_bin, I got an error saying that 
Input taxonomy database "/export/home/SemiBin-main/SemiBin_GTDB" is missing files:
- /export/home/SemiBin-main/SemiBin_GTDB_mapping
- /export/home/SemiBin-main/SemiBin_GTDB_nodes.dmp
- /export/home/SemiBin-main/SemiBin_GTDB_names.dmp
- /export/home/SemiBin-main/SemiBin_GTDB_merged.dmp

How can I get these four files - I downloaded the DB using SemiBin download_GTDB --reference-db SemiBin_GTDB, but these four files are not in my DB folder. 

Thank you

Regards,

Wisnu

**Comment by psj1997** [comment]
Hi, can you show the files downloaded with SemiBin download_GTDB and the command you used to run SemiBin?

**Comment by wisnu-adi** [comment]
the folder contains:
SemiBin_GTDB/GTDB_mapping
SemiBin_GTDB/GTDB_taxonomy
SemiBin_GTDB/GTDB.lookup
SemiBin_GTDB/GTDB_h.index
SemiBin_GTDB/GTDB.index
SemiBin_GTDB/GTDB.dbtype
SemiBin_GTDB/GTDB
SemiBin_GTDB/GTDB_h.dbtype
SemiBin_GTDB/GTDB_h
SemiBin_GTDB/GTDB.source
SemiBin_GTDB/GTDB.version

I ran 
SemiBin single_easy_bin -i final_contigs_1000.fa -r bwa_map_back_megahit_sorted.bam -o output_SemiBin  -r /export/home/SemiBin-main/SemiBin_GTDB 

I used SemiBin0.3 as well as 0.2 but it gave me the same error - missing the four files

Thanks

**Comment by psj1997** [comment]
The command should be SemiBin single_easy_bin -i final_contigs_1000.fa -r bwa_map_back_megahit_sorted.bam -o output_SemiBin -r /export/home/SemiBin-main/SemiBin_GTDB/GTDB

Shaojun

**Comment by wisnu-adi** [comment]
Hi Shaojun, 

I mistakenly wrote the command, it should have been -b instead of -r.
Anyway, adding GTDB to the reference path makes it works. Thank you.
