### ISSUE TITLE
Chromosome found in non-sequential lines. This suggests that the input file is not sorted correctly.

### ISSUE THREAD

**Issue by Lucas-Maciel** [BigDataBiology/SemiBin#47]
Hi,

I have a catalog of contigs that I mapped my reads against it and sorted to use with vamb. Recently, I found out about Semibin and I want to compare the results using the same bam files. I'm trying to use as a co-assembly. 

`SemiBin single_easy_bin -i catalogue.fna.gz -b bam/*.bam -o SemiBin`

But I get the following error:
```
#SemiBin v 0.4.0
[...]
2021-11-16 20:10:07,579 - Processing `bam/SRRyyy.bam`
2021-11-16 20:10:07,579 - Processing `bam/SRRxxxx.bam`
Input error: Chromosome S24Ck141_17031 found in non-sequential lines. This suggests that the input file is not sorted correctly.
Input error: Chromosome S26Ck141_95181 found in non-sequential lines. This suggests that the input file is not sorted correctly.
Input error: Chromosome S27Ck141_14338 found in non-sequential lines. This suggests that the input file is not sorted correctly.
Input error: Chromosome S15Ck141_317487 found in non-sequential lines. This suggests that the input file is not sorted correctly.
Input error: Chromosome S12Ck141_136850 found in non-sequential lines. This suggests that the input file is not sorted correctly.
Input error: Chromosome S8Ck141_169741 found in non-sequential lines. This suggests that the input file is not sorted correctly.
[...]
```

I don't know what should I do differently.

Thanks for your time

**Comment by psj1997** [comment]
Hi,

We use ` bedtools genomecov` to calculate the coverage. I think the error is caused bam file not sorted correctly. 
Can you try https://semibin.readthedocs.io/en/latest/generate/ to sort the bam file?

Shaojun

**Comment by luispedro** [comment]
. @Lucas-Maciel Is this still an issue?
