### ISSUE TITLE
Download GTDB as a stream

### ISSUE THREAD

**Issue by luispedro** [BigDataBiology/SemiBin#49]
Currently, `SemiBin`'s `download_gtdb` command does the following:

1. Downloads the `.tar.gz` file to a directory
2. Computes the checksum
3. If the checksum is good, uncompresses it
4. Removes the temporary .tar.gz

This is very inefficient as there is no need to store the intermediate file (which is also 23GB) and read it twice from disk. It can be done in a single pass.

An initial (quite simple in code) first step, could be to combine steps 1 and 2, thus not only avoiding the disk read, but speeding up the process too.

**Comment by luispedro** [comment]
Reopening: the first step is done in `v0.5` (streaming hash computation) and saves time, but we still save the temporary tarball.

The ideal version would be fully streamed

**Comment by luispedro** [comment]
As we now have self-supervised learning, which does not require GTDB, this is less important.

Once self-supervised learning becomes the default, this issue can probably be closed.

**Comment by dportik** [comment]
Quick question on this - so I should be able to run with `--self-supervised`,  not provide any value for `-r/--reference-db-data-dir`, and semibin will not d/l the GTDB database? I'd like to avoid a passively triggered download.

**Comment by luispedro** [comment]
Yes, if you are running with `--self-supervised`, then `-r` is ignored and GTDB will not be downloaded

**Comment by luispedro** [comment]
Closing as we are moving away from using GTDB altogether with `SemiBin2`
