### ISSUE TITLE
Update GTDB reference

### ISSUE THREAD

**Issue by fplaza** [BigDataBiology/SemiBin#58]
Hi,

Could you update the GTDB reference from r95 to r202?
Many new species are available in r202 (more particularly for the human gut) and I guess it would significantly improve results.

Best,
Florian

**Comment by psj1997** [comment]
Thanks! 

We will update this in the document later. But for now, if you want to use the r202, you can directly use the `mmseqs databases GTDB GTDB tmp` to download the latest version and use `-r` to point to this database.

Sincerely
Shaojun

**Comment by fplaza** [comment]
Thanks for the tip!
Florian
