### ISSUE TITLE
Check that --reference parameter is a valid directory

### ISSUE THREAD

**Issue by fplaza** [BigDataBiology/SemiBin#59]
Hi, 

Currently, SemiBin accepts a regular file as "--reference" parameter
https://github.com/BigDataBiology/SemiBin/blob/a0ab053aaa8e036fffb76fcc55538ee4127d8f10/SemiBin/utils.py#L26
Yet, a valid directory should be provided.

A warning indicating that the directory does not contain the expected mmseqs2 database (GTDB file) and that it will be downloaded latter would be welcome as well.

Best,
Florian

**Comment by luispedro** [comment]
Fortunately, the function `expect_file` still returns true if given a directory, so it "works" if you pass it a directory.

However, I do agree that this could be better in terms of error checking and providing feedback.

**Comment by fplaza** [comment]
Indeed. The issue title is a bit confusing!
