### ISSUE TITLE
Sample Names including special characters for multi sample binning

### ISSUE THREAD

**Issue by pangenomics** [BigDataBiology/SemiBin#68]
Hi Luis, Shaojun, and the rest of the dev team,

Thanks for the development of SemiBin! 
We recently tried to use SemiBin on a group of samples, which for processing reasons were called e.g. study_1000049+73140_METAG. Everything seemed to work fine (we used ":" as separator), but the data.csv files contained only the header line which led to an error in the training part.
We changed the sample names to the format sample1000049 etc and now it works. 

Also wanted to file this issue so others who have a similar issue can find a workaround more easily. 

Best,
Daniel

**Comment by luispedro** [comment]
This is an interesting bug. I have been able to reproduce it on my side.

We'll definitely look into it more (but it might have to wait until after Lunar New Year)
