### ISSUE TITLE
Accept a contigs coverage table generated by another tool

### ISSUE THREAD

**Issue by fplaza** [BigDataBiology/SemiBin#70]
Hi!

I was wondering if SemiBin could accept a contigs coverage table generated by another tool (e.g. jgi_summarize_bam_contig_depths) instead of computing it from the bam files?

I think it has several advantages:

- Compute the contigs coverage table once if multiple binners are used
- jgi_summarize_bam_contig_depths is faster than bedtools genomecov 
- jgi_summarize_bam_contig_depths includes an option to filter by nucleotide identity (and not bedtools genomecov). This is useful when alignments were not generated by ngless.

**Comment by luispedro** [comment]
The big thing is that we need to have the full bedtools output with the per base coverage to simulate breaking up the contigs as part of the algorithm; many other tools do not generate this output.

**Comment by fplaza** [comment]
I see.
I will try to modify the source code to filter on the fly alignments with a low percentage of identity.
