### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels...

### ISSUE THREAD

**Issue by SvetlanaUP** [BigDataBiology/SemiBin#72]
Hi, when I'm trying to install the following, I'm getting the PackagesNotFoundError

conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch-lts                                   
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.2
  - torchaudio

Current channels:

  - https://conda.anaconda.org/pytorch-lts/osx-64
  - https://conda.anaconda.org/pytorch-lts/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

THANKS!

**Comment by luispedro** [comment]
I think this is a documentation issue

```bash
conda install -c bioconda semibin
```

Should be the recommended way without all that extra stuff, which can be given as _Advanced_ or something

**Comment by luispedro** [comment]
Reopening as at least the README file still has bad instructions.

**Comment by psj1997** [comment]
OK. It seems it is also a Mac issue.
