### ISSUE TITLE
Train a model from several samples

### ISSUE THREAD

**Issue by fplaza** [BigDataBiology/SemiBin#75]
Hello,

I would like to create a model for an ecosystem currently not implemented in SemiBin.

Below is my command:

```
SemiBin train -i $(ls /projects/microreset/analysis/assembly_clean/Lapin-0*/*.fa | sort) \
--data sample*/data.csv \
--data-split sample*/data_split.csv \
-c sample*/cannot/cannot.txt \
-m 2500 \
-p 30 \
-o semibin_pretrain --mode several
```

SemiBin v0.6.0 fails with the following error:
`Error: training mode with several only used in single-sample binning!`

I don't understand it because I used the 'generate_sequence_features_single' command

Could you help me?

**Comment by psj1997** [comment]
We think these steps are correct. We evaluated the shape of the data.csv and data_split.csv before the training with several mode. Can you help to check the shape of the data.csv and data_split.csv? The shape should be (n, 138) for data.csv and (m, 136) for data_split.csv.

Sincerely
Shaojun

**Comment by fplaza** [comment]
Actually, I performed single-sample binning but computed the abundance of contigs in multiple samples (by using several bam files for each sample).

**Comment by psj1997** [comment]
Because of the algorithm design for training the model from several samples, we support this mode with single-sample binning (one bam file for every sample) for now. If you want to use several bam files, you can try to train model for every sample.

Sincerely
Shaojun

**Comment by fplaza** [comment]
Thanks. I understand but the error message is confusing as I did not perform multi-sample binning. 

What do you think is the best option:
1) create a different model for each sample by providing multiple bam files for all of them
2) create a single model with one bam file per sample and then, applying this model to each sample by providing multiple bam files

**Comment by psj1997** [comment]
```
What do you think is the best option:

1. create a different model for each sample by providing multiple bam files for all of them
2. create a single model with one bam file per sample and then, applying this model to each sample by providing multiple bam files
```
If you want to use the option2, you need to make sure that the number of multiple bam files is smaller than 5 (in this condition, SemiBin use a different way to handle the abundance feature).
From our benchmark, the option1 is better, but need more computation. And option2 is much faster if you have a pertrained model.

Sincerely
Shaojun

**Comment by fplaza** [comment]
Thank you Shaojun for the detailed answer.
I will go for option 2 as I have only a few dozen samples.

Best,
Florian
