### ISSUE TITLE
Handle 'no support' in the generation of cannot links using CAT classification

### ISSUE THREAD

**Issue by mgabriell1** [BigDataBiology/SemiBin#86]
Hi,
I have been using CAT against NCBI to perform the taxonomic classification of my contigs as explained here (https://semibin.readthedocs.io/en/latest/generate/). I then used the [script/generate_cannot_link.py](https://github.com/BigDataBiology/SemiBin/blob/main/script/generate_cannot_link.py) to generate the cannot links.
However, that script encounters problems when CAT outputs 'no support' in the classifications.

To solve this issue I simply modified lines 39 and 58 in the following way:
```
if genus1 == 'not classified' or genus2 == 'not classified' or genus1 == 'no support' or genus2 == 'no support':
    ...
```
I realize this might not be top-priority, but this fix should be rather quick.
Thanks for developing this tool!

**Comment by psj1997** [comment]
Thanks for your suggestions! We have fixed this.

Sincerely
Shaojun

**Comment by luispedro** [comment]
@psj1997 : can you add some tests for this feature?
