### ISSUE TITLE
Model training error: 'Target sequence length > 100K, over comparison pipeline limit.'

### ISSUE THREAD

**Issue by mgabriell1** [BigDataBiology/SemiBin#87]
Hi,
I have encountered this error during the training of the semi-supervised model:
```
2022-03-21 22:48:20,032 - Setting number of CPUs to 48
2022-03-21 22:48:27,350 - Start training from one sample.
2022-03-21 22:48:34,566 - Training model...
^M  0%|          | 0/20 [00:00<?, ?it/s]Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Error: Running hmmsearch fail
```
 Looking around it seems that this is not strictly related to SemiBin but more to HMM which is invoked internally.
 The command used was the one below and the inputs were generated as specified in the docs, creating the cannot-link constraints realying on a previous CAT classification (always performed following the docs' example)
```
SemiBin train -i ../assembly/contigs-fixed.fasta --data contig_output/data.csv --data-split contig_output/data_split.csv -c contig_output/cannot-link.txt -o contig_output --mode single
```
Oddly, I managed to bin another assembly (which is actually a subset of the one raising errors) and both assemblies present contigs longer than 100K.

What could be the cause of this issue?

Thanks!

**Comment by psj1997** [comment]
Thanks for your feedbacks!

We think this is a issue from the hmmsearch, can you give us more information about the contigs? Like how long the contigs are? Thanks!

Sincerely
Shaojun

**Comment by luispedro** [comment]
@mgabriell1 : if this happens reproducibly on this sample, would it be possible for you to share the data with us ? We'd not use it for anything else but to debug this issue.

**Comment by mgabriell1** [comment]
Hi,
This are the details of the two assembly that I'm testing:
```
file                   format  type  num_seqs        sum_len  min_len  avg_len     max_len     Q1     Q2     Q3     N50    
gsa_pooled_RED.fasta   FASTA   DNA    154,106    642,396,714    1,000  4,168.5   2,640,151  1,259  1,700  2,863   9,409
gsa_pooled_FULL.fasta  FASTA   DNA    328,414  1,509,700,081    1,000  4,596.9  11,270,712  1,238  1,626  2,514  19,558
```
Note that the first one (`gsa_pooled_RED`) is just a subset of the other (`gsa_pooled_FULL`). So I guess it must be some of the extra contigs which were not included in the `RED` one which cause the problem. Still both assemblies present contigs longer than 100K bp..
Also, except for the 

I re-ran this multiple times (using the same CAT cannot-link classification as, in my opinion, should be the cause for this), but I always got the same error.
I can share the data. How do we do so?

Thank you for your support!

**Comment by luispedro** [comment]
> I can share the data. How do we do so?

Thanks. Perhaps you can follow-up privately (luispedro@big-data-biology.org or shaojun@big-data-biology.org) and we will see how you can share the data privately.
