### ISSUE TITLE
Error: MD5 check failed, removing '/home/people/binson/.cache/SemiBin/mmseqs2-GTDB/GTDB_v95.tar.gz'.

### ISSUE THREAD

**Issue by B-1991-ing** [BigDataBiology/SemiBin#90]
Dear SemiBin support team,

I am running the SemiBin/0.7.0 single_easy_bin command line below. But I got error message below. what should I do to avoid it?

**The single_easy_bin command line**
cd /home/projects/XXX/people/XXX/Current_pipeline/binning/semibin
contig_fa=contig.fa
S2_bam=Sample2_TM_paired.bam
S3_bam=Sample3_TM_paired.bam
S4_bam=Sample4_TM_paired.bam
S5_bam=Sample5_TM_paired.bam
S6_bam=Sample6_TM_paired.bam
S7_bam=Sample7_TM_paired.bam
output=output
SemiBin single_easy_bin -i ${contig_fa} -b ${S2_bam} ${S3_bam} ${S4_bam} ${S5_bam} ${S6_bam} ${S7_bam} -o ${output}

**Error**
Error: MD5 check failed, removing '/home/people/binson/.cache/SemiBin/mmseqs2-GTDB/GTDB_v95.tar.gz'.

**Error file**
Attached file.
[semibin-single_easy_bin_err.txt](https://github.com/BigDataBiology/SemiBin/files/8516963/semibin-single_easy_bin_err.txt)

**Log file**
Attached file.
[semibin-single_easy_bin_log.txt](https://github.com/BigDataBiology/SemiBin/files/8516964/semibin-single_easy_bin_log.txt)

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear SemiBin support team,

**Updated**

I think it might because the wrong running path, so now  I run the command line in the path -"/home/projects/XXX/people/binson" instead of the file input and output path -"/home/projects/XXX/people/binson/Current_pipeline/binning/semibin/".

file_path=/home/projects/XXX/people/binson/Current_pipeline/binning/semibin/
contig_fa=${file_path}contig.fa
S2_bam=${file_path}Sample2_TM_paired.bam
S3_bam=${file_path}Sample3_TM_paired.bam
S4_bam=${file_path}Sample4_TM_paired.bam
S5_bam=${file_path}Sample5_TM_paired.bam
S6_bam=${file_path}Sample6_TM_paired.bam
S7_bam=${file_path}Sample7_TM_paired.bam
output=${file_path}output
refdb_dir=${file_path}mmseqs2-GTDB
SemiBin single_easy_bin -r ${refdb_dir} -i ${contig_fa} -b ${S2_bam} ${S3_bam} ${S4_bam} ${S5_bam} ${S6_bam} ${S7_bam} -o ${output}

But, using the above updated command line, I got another problem that the software wanted to download the GTDB_v95.tar.gz file to my personal directory, where only allow < 10 GB total storage. Then, I set -r/--reference-db-data-dir from the default directory to the current "refdb_dir" now. Hope it works.

Best,

Bing

**Comment by psj1997** [comment]
Hi, Bing

It seems that the Internet issue when downloading the GTDB dataset. Do you have fixed this?

Sincerely
Shaojun

**Comment by B-1991-ing** [comment]
Hi Shaojun,

Thank you very much for your reply. It works now. 

The reason for first error "" is I didn't set parameter "-r". My personal directory only allows 10GB data, while GTDB db more than 20GB. 

-r/--reference-db-data-dir: GTDB reference directory (Default: $HOME/.cache/SemiBin/mmseqs2-GTDB). SemiBin will lazily download GTDB if it is not found there.

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear SemiBin support team,

One more question, do we need to download the mmseqs2-GTDB when running the SemiBin? As our HPC support team told me that I am filling up my home directory. Or, could we only delete the mmseqs2-GTDB db every time we finish the SemiBin running?

I actually downloaded the mmseqs2-GTDB db not directly to my home directory but another dir.

Best,

Bing

**Comment by psj1997** [comment]
Hi Bing

The mmseqs2-GTDB database is used to annotate the contigs to generate the inputs for the SemiBin. 

It will just be downloaded once (SemiBin will detect if GTDB exists in the path set by -r parameter). 

Also you can delete it after the running and download it again next time.

Sincerely
Shaojun

**Comment by B-1991-ing** [comment]
Okay, get it. Thank you very much, Shaojun.
