### ISSUE TITLE
SemiBin resources and runtime when ran over CAMI2 data

### ISSUE THREAD

**Issue by Paupiera** [BigDataBiology/SemiBin#94]
Hi,

I am trying to run SemiBin over the CAMI2 Oral and CAMI2 Skin datasets so I can reproduce the results claimed on the SemiBin publication. To do so I am trying to run the following code:

`date=020522
d=oral
contigs_file=../Data/data/"$d"/contigs.fna
bam_files=bam_files_sorted/"$d"/*_sorted.bam
SemiBin multi_easy_bin -i $contigs_file -b $bam_files -o multi_easy_bin_cami/semibin_"$d"_multy_easy_bin_"$date" --separator C  -t 20`

Resources set for the run:
150 gb of RAM
1 GPU
20 CPU cores

Unfortunately after 2 days, yet it has not finished.

1. Am I doing something wrong?
2. Should I set more resources?
 
Thank you so much for your help, 
Pau

**Comment by luispedro** [comment]
Thanks for the bugreport

Can you post the full logs from running SemiBin?

**Comment by Paupiera** [comment]
Yes of course. 
I ran it in a computer cluster that generates standard error and standard output files. Attach you will find both. 
[semibin_oral.err.txt](https://github.com/BigDataBiology/SemiBin/files/8650994/semibin_oral.err.txt)
[semibin_oral.out.txt](https://github.com/BigDataBiology/SemiBin/files/8650998/semibin_oral.out.txt)

**Comment by psj1997** [comment]
Thanks! 

`100%|██████████| 20/20 [29:15:23<00:00, 5266.19s/it]`

Can you check if you run SemiBin with cuda (especially for model training)? 
It seems you run with CPU and it takes 30 hours to finish the model training of one sample (there are 10 samples). 
If you use GPU, I think it is about 40 minutes (will be much faster).

Sincerely
Shaojun

**Comment by Paupiera** [comment]
I will try out and report it here, I cannot find a specific flag to use GPU so I guess installing Pytorch with GPU support and a GPU available should be enough for SemiBin to leverage the GPU.

Do you know how much memory should I set for this kind of runs?   

Thanks for your help,
Pau

**Comment by psj1997** [comment]
`I will try out and report it here, I cannot find a specific flag to use GPU so I guess installing Pytorch with GPU support and a GPU available should be enough for SemiBin to leverage the GPU.`

Actually yes. You can try `torch.cuda.is_available()`. If the return value is True, SemiBin will automatically use GPU version.

`Do you know how much memory should I set for this kind of runs?`

150G is actually enough. 

Sincerely
Shaojun

**Comment by luispedro** [comment]
> You can try torch.cuda.is_available(). If the return value is True, SemiBin will automatically use GPU version.

I agree with @Paupiera that a flag would be a good idea. Probably a ternary flag:

- `auto`: current behavior
- `gpu`: always use GPU (and fail if gpu is not found)
- `cpu`: always use CPU even if GPU is found (not sure why the user would want to choose this, tbh)

Probably it's a good idea to print out whether a GPU is found in the `auto` setting

**Comment by Paupiera** [comment]
I successfully ran SemiBin over the Oral CAMI2 dataset on the GPU, 20 CPU cores and 150Gb, takin around 20 hours. 

Thank you so much for your help,
Best,
Pau
