### ISSUE TITLE
Is it okay to directly use the IDBAUD-assembled contig.fa and corresponding metawrap-binning generated .bam file as the input?

### ISSUE THREAD

**Issue by B-1991-ing** [BigDataBiology/SemiBin#99]
Dear Semibin support team,

I directly used the IDBAUD-assembled contig.fa and metawrap-binning generated .bam file as the input of the semibin binning.

The sequence name in the IDBAUD-assembled contig.fa: **contig-<contig_id> length_<length> read_count_<read_count>**
The sequence name in  metawrap-binning generated *.bam: **contig-<contig_id> length_<length> read_count_<read_count>**

The command line I used
[semibin_single_easy_bin_command_line.txt](https://github.com/BigDataBiology/SemiBin/files/9039780/semibin_single_easy_bin_command_line.txt)

Error file
[semibin-single_easy_bin.err.txt](https://github.com/BigDataBiology/SemiBin/files/9039689/semibin-single_easy_bin.err.txt)

Log file
[semibin-single_easy_bin.log](https://github.com/BigDataBiology/SemiBin/files/9039690/semibin-single_easy_bin.log)

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear Semibin support team,

I already ran the SemiBin single_easy_bin twice **directly with the IDBAUD-assembled contig.fa and and metawrap binning generated *.bam file** and also ran one time with **the IDBAUD-assembled id-only contig.fa and and metawrap binning generated *.bam file**. I always 100 bins, but each result with slight different bin output.

My IDBAUD-assembled contig.fa:
>contig-100_0 length_566717 read_count_46772115
[bin.txt](https://github.com/BigDataBiology/SemiBin/files/9046448/bin.txt)

My IDBAUD-assembled id-only contig.fa:
>contig-100_0
[bin_idonly.txt](https://github.com/BigDataBiology/SemiBin/files/9046439/bin_idonly.txt)

So, is it actually normal? As far as now, I really didn't get error from three running results.

Best,

Bing

**Comment by psj1997** [comment]
Thanks for your attention of SemiBin.


I think for the model training, there will be a slight difference between different runs. You can check the data.csv and data_split.csv between different runs and if they are the same (if means the input is right), the difference from the model training is very small.


Sincerely
Shaojun






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "BigDataBiology/SemiBin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 晚上8:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [BigDataBiology/SemiBin] Should the sequence names of the contig.fa and that of the .bam file the same? (Issue #99)





 
Dear Semibin support team,
 
I already ran the SemiBin single_easy_bin twice *directly with the IDBAUD-assembled contig.fa and and metawrap binning generated .bam file and also ran one time with *the IDBAUD-assembled id-only contig.fa and and metawrap binning generated .bam file. I always 100 bins, but each result with slight different bin output.
 
My IDBAUD-assembled contig.fa:
  
contig-100_0 length_566717 read_count_46772115
 bin.txt
  
My IDBAUD-assembled id-only contig.fa:
  
contig-100_0
 bin_idonly.txt
  
So, is it actually normal? As far as now, I really didn't get error from three running results.
 
Best,
 
Bing

**Comment by B-1991-ing** [comment]
Hi Shaojun,

Thank you very much for your reply.

I checked the data.csv and data_split.csv from my three running ouputs, their file size are exactly same. For the output bins, only slight difference there.

So, it seems like no problem that I directly use the IDBAUD-assembled contig.fa and metawrap-binning generated .bam file as the input of the semibin binning?

Best,
Bing

**Comment by B-1991-ing** [comment]
Okay, thank you very much for your reply. I will check it.

Best,
Bing

**Comment by luispedro** [comment]
@B-1991-ing: it seems to me that this issue is fixed, so I'm closing, but please reopen if there are any lingering questions
